import { IntakeInput } from "./types.js";

export const requiredProjectFiles = [
  "Planning/Architect_Pack.md",
  "Planning/Technical_Blueprint.md",
  "Planning/Handoff_Prompt.md",
  "Planning/Validation_Report.md",
  "Planning/Governance/Current_State.md",
  "Planning/Governance/Decisions.md",
  "Planning/Governance/Risks.md",
  "Planning/Governance/Open_Questions.md",
  "Planning/Governance/Acceptance_Criteria.md",
  "Sprints/Sprint_001/Sprint_Plan.md",
  "Sprints/Sprint_001/Builder_Dry_Run.md",
  "Sprints/Sprint_001/Implementation_Log.md",
  "Sprints/Sprint_001/Test_Report.md",
  "Sprints/Sprint_001/Acceptance_Report.md",
  "Docs/Product_Requirements.md",
  "Docs/User_Roles.md",
  "Docs/Methodology_Guide.md",
  "Docs/System_Tools.md",
  "Docs/Success_Criteria.md"
] as const;

const list = (items: string[]) => items.length ? items.map((item) => `- ${item}`).join("\n") : "- TBD";

export function userAgreementTemplate(intake: IntakeInput): string {
  return `# USER AGREEMENT
  
  ## Agreement for ${intake.projectName}
  
  This agreement is between the User and the Service Provider of ${intake.projectName}.
  
  ## 1. Terms of Use
  By using the service, you agree to follow all architectural and security guidelines provided in the technical blueprint.
  
  ## 2. User Responsibilities
  Users are responsible for maintaining the confidentiality of their accounts.
  
  ## 3. Limitation of Liability
  The service is provided "as is" without warranties of any kind.
  
  ## 4. Governing Law
  This agreement is governed by the laws of the jurisdiction where the service is hosted.
  
  ---
  *Auto-generated by Shiptec Command Center*
  `;
}

export function privacyPolicyTemplate(intake: IntakeInput): string {
  return `# PRIVACY POLICY
  
  ## Privacy Policy for ${intake.projectName}
  
  Last Updated: ${new Date().toISOString()}
  
  ## 1. Information Collection
  We collect only the information necessary to provide the services described in the Product Requirements.
  
  ## 2. Use of Data
  Data is used strictly for functional purposes and is isolated by tenant.
  
  ## 3. Third-Party Sharing
  We do not share user data with third parties except for necessary integrations: ${intake.toolsAndIntegrations.join(", ") || "None"}.
  
  ## 4. Data Security
  We implement industry-standard security measures as outlined in the SECURITY.md artifact.
  
  ---
  *Auto-generated by Shiptec Command Center*
  `;
}

export function productRequirementsTemplate(intake: IntakeInput): string {
  return `# Product Requirements

## Project
${intake.projectName}

## Product Summary
${intake.productSummary}

## Business Problem
${intake.businessProblem}

## MVP Definition
${intake.mvpDefinition}

## Current Workflow
${intake.currentWorkflow}

## Desired Workflow
${intake.desiredWorkflow}
`;
}

export function userRolesTemplate(intake: IntakeInput): string {
  return `# User Roles

## Target Users
${list(intake.targetUsers)}
`;
}

export function successCriteriaTemplate(intake: IntakeInput): string {
  return `# Success Criteria

${list(intake.successCriteria)}
`;
}

export function methodologyGuideTemplate(): string {
  return `# Methodology Guide

Shiptec uses a strict Architect-Builder split.

## Architect
- Captures requirements.
- Creates explicit blueprints.
- Defines acceptance criteria.
- Reviews Builder output.

## Builder
- Reads the source-of-truth planning files.
- Produces a dry run before edits.
- Implements only approved sprint scope.
- Records checks, results, and acceptance status.
`;
}

export function systemToolsTemplate(intake: IntakeInput): string {
  return `# System Tools

## Required Tools and Integrations
${list(intake.toolsAndIntegrations)}

## Technical Constraints
${list(intake.technicalConstraints)}
`;
}

export function architectPackTemplate(intake: IntakeInput): string {
  return `# Architect Pack
  
## Product Intent
${intake.productSummary}

## Business Problem
${intake.businessProblem}

## Users and Roles
${list(intake.targetUsers)}

## Future Workflow
${intake.desiredWorkflow}

## MVP Scope
${intake.mvpDefinition}

## Success Criteria
${list(intake.successCriteria)}

## Integrations
${list(intake.toolsAndIntegrations)}

## Constraints
${list(intake.technicalConstraints)}

## Skills & Knowledge Sources
- **Verified Skills:** ${intake.skillsUrl.length ? intake.skillsUrl.join(", ") : "None provided"}
- **Reference Projects (Knowledge):** ${intake.knowledgeUrl.length ? intake.knowledgeUrl.join(", ") : "None provided"}

## Risks
${list(intake.knownRisks)}

## Open Questions
${list(intake.openQuestions)}
`;
}

export function technicalBlueprintTemplate(intake: IntakeInput): string {
  return `# Technical Blueprint
  
## Default Stack
- Node.js
- TypeScript
- Express
- simple-git
- @octokit/rest
- Markdown planning artifacts

## Initial Architecture
- API layer handles command center requests.
- Domain services perform validation, health scoring, sprint planning, and file provisioning.
- Filesystem service owns all project artifact writes.
- Git service owns local Git and GitHub readiness checks.

## Knowledge Base & Skills Reference
- **Implementation Skills:** ${intake.skillsUrl.length ? intake.skillsUrl.join(", ") : "Use standard industry patterns"}
- **Customization Knowledge:** ${intake.knowledgeUrl.length ? intake.knowledgeUrl.join(", ") : "Based on provided product requirements"}

## Project Constraints
${list(intake.technicalConstraints)}
`;
}

export function handoffPromptTemplate(intake: IntakeInput): string {
  return `# Handoff Prompt

You are the Builder for ${intake.projectName}.

Before editing files, read:
- Planning/Architect_Pack.md
- Planning/Technical_Blueprint.md
- Planning/Governance/Acceptance_Criteria.md
- Planning/Governance/Current_State.md
- Planning/Governance/Decisions.md
- Planning/Governance/Risks.md
- Planning/Governance/Open_Questions.md

Produce a Builder Dry Run and Sprint Plan before implementation. Do not invent missing requirements.
`;
}

export function currentStateTemplate(intake: IntakeInput): string {
  return `# Current State

## Status
Initialized from structured intake.

## Product
${intake.projectName}

## Last Updated
${new Date().toISOString()}
`;
}

export function decisionsTemplate(): string {
  return `# Decisions

| Date | Decision | Rationale | Owner |
| --- | --- | --- | --- |
| TBD | Initial architecture uses TypeScript and Express. | Matches Shiptec default stack. | Architect |
`;
}

export function risksTemplate(intake: IntakeInput): string {
  return `# Risks

${list(intake.knownRisks)}
`;
}

export function openQuestionsTemplate(intake: IntakeInput): string {
  return `# Open Questions

${list(intake.openQuestions)}
`;
}

export function acceptanceCriteriaTemplate(intake: IntakeInput): string {
  return `# Acceptance Criteria

${list(intake.successCriteria)}
`;
}

export function sprintPlanTemplate(sprintId: string): string {
  return `# ${sprintId} Sprint Plan

## Goal
Deliver the first validated vertical slice.

## Scope
- Confirm planning source files exist.
- Create or update Builder Dry Run.
- Implement approved functionality only.
- Run available checks.

## Out of Scope
- Unapproved feature expansion.
- Silent overwrites of user-authored files.
`;
}

export function builderDryRunTemplate(sprintId: string): string {
  return `# ${sprintId} Builder Dry Run

## Files To Read First
- Planning/Architect_Pack.md
- Planning/Technical_Blueprint.md
- Planning/Governance/Acceptance_Criteria.md
- Planning/Governance/Current_State.md
- Planning/Governance/Decisions.md
- Planning/Governance/Risks.md
- Planning/Governance/Open_Questions.md

## Intended File Operations
- Create missing implementation files for approved sprint scope.
- Update implementation and test logs after checks run.

## Pre-Flight Checklist
- Validation report is not fail.
- Acceptance criteria are specific.
- Blocking open questions are resolved or explicitly marked non-blocking.
`;
}

export function implementationLogTemplate(): string {
  return `# Implementation Log

No implementation work has been recorded yet.
`;
}

export function testReportTemplate(): string {
  return `# Test Report

No tests have been run for this sprint yet.
`;
}

export function acceptanceReportTemplate(): string {
  return `# Acceptance Report

Acceptance review is pending.
`;
}

// ==========================================
// Phase 1 - Principal Architect Templates
// ==========================================

export function architectureOverviewTemplate(intake: IntakeInput): string {
  return `# ARCHITECTURE OVERVIEW

## System Topology
- Client-Server Architecture.
- API-First design pattern.
- Separated UI (Frontend) and Business Logic (Backend).

## Primary Goal
${intake.productSummary}

## Architecture Directives
1. Strict adherence to contracts in API_SPEC.md and Database schemas.
2. Absolutely no business logic in UI templates/components.
3. Decoupled services for third-party integrations: ${list(intake.toolsAndIntegrations)}
`;
}

export function technicalBlueprintTemplate_v2(intake: IntakeInput): string {
  return `# Technical Blueprint (Hard Constraints)

## Default Stack
- Runtime: Node.js (v22)
- Language: TypeScript
- Web Framework: Express
- Integrations: simple-git, @octokit/rest

## Code Style & Rules
- Absolute strict typing (no 'any').
- Functional programming preferred for domain logic.
- Absolute zero-error stability required before any release.
`;
}

export function handoffPromptTemplate_v2(intake: IntakeInput): string {
  return `# Handoff Prompt

You are the Builder for ${intake.projectName}.

Before editing files, read:
- Planning/Architect_Pack.md
- Planning/Technical_Blueprint.md
- Planning/Governance/Acceptance_Criteria.md
- Planning/Governance/Current_State.md

Produce a Builder Dry Run and Sprint Plan before implementation. Do not invent missing requirements.
`;
}

export function validationReportTemplate(): string {
  return `# Validation Report

Validation of requirements pending. Run the Validate action.
`;
}

export function currentStateTemplate_v2(intake: IntakeInput): string {
  return `# Current State

## Status
Initialized from structured intake.

## Product
${intake.projectName}

## Last Updated
${new Date().toISOString()}
`;
}

export function decisionsTemplate_v2(): string {
  return `# Decisions

| Date | Decision | Rationale | Owner |
| --- | --- | --- | --- |
| TBD | Initial architecture uses TypeScript and Express. | Matches Shiptec default stack. | Architect |
`;
}

export function risksTemplate_v2(intake: IntakeInput): string {
  return `# Risks

${list(intake.knownRisks)}
`;
}

export function openQuestionsTemplate_v2(intake: IntakeInput): string {
  return `# Open Questions

${list(intake.openQuestions)}
`;
}

export function acceptanceCriteriaTemplate_v2(intake: IntakeInput): string {
  return `# Acceptance Criteria

${list(intake.successCriteria)}
`;
}

export function databaseDesignTemplate(intake: IntakeInput): string {
  return `# DATABASE DESIGN

## Database Engine
- Recommended: PostgreSQL (for multi-tenant safety/schemas).

## Core Schemas / Models
- **Tenant:** id, domain, status, createdAt
- **User:** id, tenantId, email, role, passwordHash
- **Profile:** id, userId, firstName, lastName

## Isolation Strategy
- Row-Level Security (RLS) or schema-per-tenant to prevent cross-tenant data leaks.
`;
}

export function apiSpecTemplate(intake: IntakeInput): string {
  return `# API SPECIFICATION (REST Contracts)

## Base URL
\`/api/v1\`

## Authentication Headers
- \`Authorization: Bearer <token>\`

## Endpoints
- **POST** \`/auth/login\`
- **GET** \`/tenants\`
- **POST** \`/tenants\`
`;
}

export function authTemplate(): string {
  return `# AUTHENTICATION & AUTHORIZATION

## Strategy
- JSON Web Tokens (JWT) for stateless sessions.
- Multi-tenant token claim payload.

## Roles
- SuperAdmin (Platform level)
- Admin (Tenant level)
- User (General staff/teachers)
`;
}

export function paymentsTemplate(): string {
  return `# PAYMENTS & BILLING

## Engine
- Recommended: Stripe or comparable provider.

## Webhooks
- Handlers for asynchronous payment events (success, failed, cancelled).
`;
}

export function securityTemplate(): string {
  return `# SECURITY REQUIREMENTS

## Policy
1. Multi-tenant isolation at the database level.
2. Input validation for all public endpoints.
3. Rate limiting on public-facing APIs.
`;
}

export function frontendTemplate(): string {
  return `# FRONTEND SPECIFICATION

## Structure
- Pages, Components, and Hooks separation.
- Component lifecycle independent of API state.
`;
}

export function backendTemplate(): string {
  return `# BACKEND SPECIFICATION

## Layers
- Controllers (HTTP interface)
- Services (Business logic)
- Repositories (Data access)
`;
}

export function testingTemplate(): string {
  return `# TESTING STRATEGY

## Coverage Goal
- 85%+ statement coverage.

## Suites
- Unit: business logic/services.
- Integration: DB/API boundaries.
`;
}

export function deploymentTemplate(): string {
  return `# DEPLOYMENT CONFIGURATION

## Targets
- Production: AWS, Render, or Firebase Hosting.
- CI/CD: GitHub Actions.
`;
}
